/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoadminsys.ui;

import infoadminsys.cls.Student;

/**
 *
 * @author lsh
 */
public class AccoutManageUI extends javax.swing.JFrame {

    /**
     * Creates new form AccoutManageUI
     */
    public AccoutManageUI() {
        initComponents();
        jLabel_account2.setText(Student.id);
        jLabel_type2.setText(Student.type);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_account1 = new javax.swing.JLabel();
        jLabel_account2 = new javax.swing.JLabel();
        jLabel_type1 = new javax.swing.JLabel();
        jLabel_type2 = new javax.swing.JLabel();
        jTextField_oldPass = new javax.swing.JTextField();
        jTextField_newPass2 = new javax.swing.JTextField();
        jLabel_oldPass = new javax.swing.JLabel();
        jLabel_newPass1 = new javax.swing.JLabel();
        jLabel_newPass2 = new javax.swing.JLabel();
        jTextField_newPass1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_account1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_account1.setText("用户名：");

        jLabel_account2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_account2.setToolTipText("");

        jLabel_type1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_type1.setText("账号类型：");

        jLabel_type2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jTextField_oldPass.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jTextField_newPass2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_newPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_newPass2ActionPerformed(evt);
            }
        });

        jLabel_oldPass.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_oldPass.setText("旧密码：");

        jLabel_newPass1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_newPass1.setText("新密码：");

        jLabel_newPass2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_newPass2.setText("确认新密码 ：");

        jTextField_newPass1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_newPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_newPass1ActionPerformed(evt);
            }
        });

        jButton1.setText("修改密码");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("返回");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_account1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_type1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_oldPass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_newPass1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_newPass2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_account2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_newPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_type2))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(120, 120, 120))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_newPass1, jTextField_newPass2, jTextField_oldPass});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_account1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_account2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_type1)
                    .addComponent(jLabel_type2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_oldPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_newPass1)
                    .addComponent(jTextField_newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_newPass2)
                    .addComponent(jTextField_newPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_newPass1, jTextField_newPass2, jTextField_oldPass});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_newPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_newPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_newPass1ActionPerformed

    private void jTextField_newPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_newPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_newPass2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_account1;
    private javax.swing.JLabel jLabel_account2;
    private javax.swing.JLabel jLabel_newPass1;
    private javax.swing.JLabel jLabel_newPass2;
    private javax.swing.JLabel jLabel_oldPass;
    private javax.swing.JLabel jLabel_type1;
    private javax.swing.JLabel jLabel_type2;
    private javax.swing.JTextField jTextField_newPass1;
    private javax.swing.JTextField jTextField_newPass2;
    private javax.swing.JTextField jTextField_oldPass;
    // End of variables declaration//GEN-END:variables
}
