/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoadminsys.ui;

import javax.swing.JOptionPane;
import infoadminsys.util.*;
import infoadminsys.cls.*;
import java.sql.SQLException;
import java.util.*;

/**
 *
 * @author lsh
 */
public class AccountManageUI extends javax.swing.JFrame {

    /**
     * Creates new form AccoutManageUI
     */
    private String username;
    private boolean sudo;

    public AccountManageUI() {
    }

    public AccountManageUI(String id, String type, boolean status) {
        username = id; sudo=status;
        initComponents();
        jLabel_account2.setText(id);
        jLabel_type2.setText(type);
        jLabel_oldPass.setVisible(!sudo);
        jPassword_old.setVisible(!sudo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_account1 = new javax.swing.JLabel();
        jLabel_account2 = new javax.swing.JLabel();
        jLabel_type1 = new javax.swing.JLabel();
        jLabel_type2 = new javax.swing.JLabel();
        jLabel_oldPass = new javax.swing.JLabel();
        jLabel_newPass1 = new javax.swing.JLabel();
        jLabel_newPass2 = new javax.swing.JLabel();
        jButton_modify = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jPassword_old = new javax.swing.JPasswordField();
        jPassword_new1 = new javax.swing.JPasswordField();
        jPassword_new2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_account1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_account1.setText("用户名：");

        jLabel_account2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_account2.setToolTipText("");

        jLabel_type1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_type1.setText("账号类型：");

        jLabel_type2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel_oldPass.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_oldPass.setText("旧密码：");

        jLabel_newPass1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_newPass1.setText("新密码：");

        jLabel_newPass2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_newPass2.setText("确认新密码 ：");

        jButton_modify.setText("修改密码");
        jButton_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifyActionPerformed(evt);
            }
        });

        jButton_back.setText("返回");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jPassword_old.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jPassword_new1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jPassword_new2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_account1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_type1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_oldPass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_newPass1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_newPass2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_account2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_type2)
                    .addComponent(jPassword_old, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword_new1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_modify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_back)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_account1)
                    .addComponent(jLabel_account2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_type1)
                    .addComponent(jLabel_type2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPassword_old, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_oldPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_newPass1)
                    .addComponent(jPassword_new1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_newPass2)
                    .addComponent(jPassword_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_modify)
                    .addComponent(jButton_back))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePassword(String password) throws SQLException {
        String sql="UPDATE userpass SET password=? WHERE username=?;";
        List<Object> param=new ArrayList<>();
        param.add(password);
        param.add(username);
        JdbcUtil jdbcUtil=new JdbcUtil();
        jdbcUtil.getConnection();
        jdbcUtil.updateByPreparedStatement(sql, param);
    }
    
    private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed
        // TODO add your handling code here:
        String passOld = new String(jPassword_old.getPassword()).trim();
        String passNew1 = new String(jPassword_new1.getPassword()).trim();
        String passNew2 = new String(jPassword_new2.getPassword()).trim();
        if (!passNew1.equals(passNew2)) {
            JOptionPane.showMessageDialog(this, "两次新密码不一致！", "提示信息", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (passOld.length()==0 || passNew1.length()==0) {
            JOptionPane.showMessageDialog(this, "密码不能为空！", "提示信息", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LoginUtil loginUtil = new LoginUtil();
        UserPass result = loginUtil.Login(new UserPass(username, passOld));
        if (!sudo && result == null) {
            JOptionPane.showMessageDialog(this, "旧密码错误！", "提示信息", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            try {
                updatePassword(passNew1);
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(this,"密码修改失败!\n"+e.getMessage(),"提示信息",JOptionPane.WARNING_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "密码修改成功!", "提示信息", JOptionPane.WARNING_MESSAGE);
            jPassword_old.setText("");
            jPassword_new1.setText("");
            jPassword_new2.setText("");
        }
    }//GEN-LAST:event_jButton_modifyActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_modify;
    private javax.swing.JLabel jLabel_account1;
    private javax.swing.JLabel jLabel_account2;
    private javax.swing.JLabel jLabel_newPass1;
    private javax.swing.JLabel jLabel_newPass2;
    private javax.swing.JLabel jLabel_oldPass;
    private javax.swing.JLabel jLabel_type1;
    private javax.swing.JLabel jLabel_type2;
    private javax.swing.JPasswordField jPassword_new1;
    private javax.swing.JPasswordField jPassword_new2;
    private javax.swing.JPasswordField jPassword_old;
    // End of variables declaration//GEN-END:variables
}
