/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoadminsys.ui;

import javax.swing.JOptionPane;
import infoadminsys.cls.*;
import infoadminsys.util.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.table.TableModel;
import java.util.*;
import java.awt.Font;
import java.awt.Image;
import java.text.ParseException;
import javax.swing.ImageIcon;

/**
 *
 * @author lsh
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentUI
     */
    private String id;
    private Administrator admin;
    private List<SelectedCourse> SCList = new ArrayList<>();
    final private SelectedCourseUtil SCUtil = new SelectedCourseUtil();
    
    private Object[][] getCourses(){
        int rowNum=SCList.size();
        Object[][] courses=new Object[rowNum][3];
        for(int i=0;i<rowNum;i++) {
            courses[i][0]=SCList.get(i).course_id;
            courses[i][1]=SCList.get(i).course_name;
            courses[i][2]=SCList.get(i).teacher_name;
        }
        return courses;
    }
    
    private TableModel SCTableModel() {
        return new javax.swing.table.DefaultTableModel(getCourses(),
                new String[]{
                    "课程号", "课程名称", "教师"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }
    
    private Object[][] getScores(){
        int rowNum=SCList.size();
        Object[][] scores=new Object[rowNum][3];
        for(int i=0;i<rowNum;i++) {
            scores[i][0]=SCList.get(i).course_id;
            scores[i][1]=SCList.get(i).course_name;
            scores[i][2]=SCList.get(i).score;
        }
        return scores;
    }
    
    private TableModel scoreTableModel() {
        return new javax.swing.table.DefaultTableModel(getScores(),
                new String[]{
                    "课程号", "课程名称", "成绩"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }
    
    private void setSearchIcon()
    {
        ImageIcon icon=new ImageIcon("/Users/lsh/Desktop/Workspace/NetBeansProjects/InfoAdminSys/image/search.png");
        icon.setImage(icon.getImage().getScaledInstance(24,24,Image.SCALE_DEFAULT));
        jLabel_search1.setIcon(icon);
        jLabel_search2.setIcon(icon);
    }
    
    private void adjust()
    {
        jPanel_student.setLayout(null);
        jLabel_search1.setBounds(20,0,24,24);
        jTextField_teaID.setBounds(54,3,132,20);
        jTextField_teaName.setBounds(183,3,138,20);
        jComboBox_teaDepart.setBounds(317,4,220,20);
        jTextField_teaMajor.setBounds(531,3,244,20);
        
        jPanel_teacher.setLayout(null);
        jLabel_search2.setBounds(20,0,24,24);
        jTextField_stuID1.setBounds(54,3,132,20);
        jTextField_stuName1.setBounds(183,3,138,20);
        jComboBox_stuDepart1.setBounds(317,4,220,20);
        jTextField_stuMajor1.setBounds(531,3,244,20);
        
        jTable_student.getTableHeader().setFont(new Font("Lucida Grande", 0, 13));
        jTable_teacher.getTableHeader().setFont(new Font("Lucida Grande", 0, 13));

    }
    
    public AdminUI() {
        //SCList=SCUtil.downloadData(id);
        initComponents();
        setSearchIcon();
        adjust();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_student = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_student = new javax.swing.JTable();
        jTextField_teaID = new javax.swing.JTextField();
        jTextField_teaName = new javax.swing.JTextField();
        jTextField_teaMajor = new javax.swing.JTextField();
        jComboBox_teaDepart = new javax.swing.JComboBox<>();
        jLabel_search1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel_teacher = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_teacher = new javax.swing.JTable();
        jTextField_stuID1 = new javax.swing.JTextField();
        jTextField_stuName1 = new javax.swing.JTextField();
        jTextField_stuMajor1 = new javax.swing.JTextField();
        jComboBox_stuDepart1 = new javax.swing.JComboBox<>();
        jLabel_search2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel_course = new javax.swing.JPanel();
        jPanel_account = new javax.swing.JPanel();
        jLabel_account = new javax.swing.JLabel();
        jLabel_hello = new javax.swing.JLabel();
        jLabel_logOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 577));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel_student.setPreferredSize(new java.awt.Dimension(800, 522));

        jTable_student.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jTable_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "序号", "学号", "姓名", "学院", "专业"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_student.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable_student.setAutoscrolls(false);
        jTable_student.setColumnSelectionAllowed(true);
        jTable_student.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_student);
        jTable_student.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable_student.getColumnModel().getColumnCount() > 0) {
            jTable_student.getColumnModel().getColumn(0).setResizable(false);
            jTable_student.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable_student.getColumnModel().getColumn(1).setResizable(false);
            jTable_student.getColumnModel().getColumn(1).setPreferredWidth(160);
            jTable_student.getColumnModel().getColumn(2).setResizable(false);
            jTable_student.getColumnModel().getColumn(2).setPreferredWidth(170);
            jTable_student.getColumnModel().getColumn(3).setResizable(false);
            jTable_student.getColumnModel().getColumn(3).setPreferredWidth(270);
            jTable_student.getColumnModel().getColumn(4).setResizable(false);
            jTable_student.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        jLabel_search1.setToolTipText("");
        jLabel_search1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_search1MouseClicked(evt);
            }
        });

        jButton1.setText("导出");

        jButton2.setText("导入");

        jButton3.setText("删除选中");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("查看详细/修改");

        javax.swing.GroupLayout jPanel_studentLayout = new javax.swing.GroupLayout(jPanel_student);
        jPanel_student.setLayout(jPanel_studentLayout);
        jPanel_studentLayout.setHorizontalGroup(
            jPanel_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_studentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_studentLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_teaID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_teaName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox_teaDepart, 0, 223, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_teaMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_studentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        jPanel_studentLayout.setVerticalGroup(
            jPanel_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_studentLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_teaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_teaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_teaDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_teaMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("学生信息", jPanel_student);

        jPanel_teacher.setPreferredSize(new java.awt.Dimension(800, 522));

        jTable_teacher.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jTable_teacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "序号", "工号", "姓名", "学院", "职称"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_teacher.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable_teacher.setAutoscrolls(false);
        jTable_teacher.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_teacher);
        jTable_teacher.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable_teacher.getColumnModel().getColumnCount() > 0) {
            jTable_teacher.getColumnModel().getColumn(0).setResizable(false);
            jTable_teacher.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable_teacher.getColumnModel().getColumn(1).setResizable(false);
            jTable_teacher.getColumnModel().getColumn(1).setPreferredWidth(160);
            jTable_teacher.getColumnModel().getColumn(2).setResizable(false);
            jTable_teacher.getColumnModel().getColumn(2).setPreferredWidth(170);
            jTable_teacher.getColumnModel().getColumn(3).setResizable(false);
            jTable_teacher.getColumnModel().getColumn(3).setPreferredWidth(270);
            jTable_teacher.getColumnModel().getColumn(4).setResizable(false);
            jTable_teacher.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        jLabel_search2.setToolTipText("");
        jLabel_search2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_search2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_search2MouseClicked(evt);
            }
        });

        jButton5.setText("导出");

        jButton6.setText("导入");

        jButton7.setText("删除选中");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("查看详细/修改");

        javax.swing.GroupLayout jPanel_teacherLayout = new javax.swing.GroupLayout(jPanel_teacher);
        jPanel_teacher.setLayout(jPanel_teacherLayout);
        jPanel_teacherLayout.setHorizontalGroup(
            jPanel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_teacherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel_teacherLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_stuID1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_stuName1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox_stuDepart1, 0, 223, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_stuMajor1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_teacherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(20, 20, 20))
        );
        jPanel_teacherLayout.setVerticalGroup(
            jPanel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_teacherLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_stuID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_stuName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_stuDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_stuMajor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jTabbedPane1.addTab("教师信息", jPanel_teacher);

        jPanel_course.setPreferredSize(new java.awt.Dimension(800, 576));

        javax.swing.GroupLayout jPanel_courseLayout = new javax.swing.GroupLayout(jPanel_course);
        jPanel_course.setLayout(jPanel_courseLayout);
        jPanel_courseLayout.setHorizontalGroup(
            jPanel_courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel_courseLayout.setVerticalGroup(
            jPanel_courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("课程信息", jPanel_course);

        javax.swing.GroupLayout jPanel_accountLayout = new javax.swing.GroupLayout(jPanel_account);
        jPanel_account.setLayout(jPanel_accountLayout);
        jPanel_accountLayout.setHorizontalGroup(
            jPanel_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel_accountLayout.setVerticalGroup(
            jPanel_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("账号信息", jPanel_account);

        jLabel_account.setText("账号管理");
        jLabel_account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_accountMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_accountMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_accountMouseEntered(evt);
            }
        });

        jLabel_hello.setText("您好,");

        jLabel_logOut.setText("注销");
        jLabel_logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logOutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_logOutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_logOutMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_hello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_account, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_logOut)
                    .addComponent(jLabel_account, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_hello, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel_account, jLabel_logOut});

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_accountMouseClicked
        // TODO add your handling code here:
        setEnabled(false);
        AccountManageUI AM = new AccountManageUI(admin.id, admin.type);
        AM.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        AM.setLocationRelativeTo(this);
        AM.setAlwaysOnTop(true);
        AM.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                setEnabled(true);
            }
        });
        AM.setVisible(true);
    }//GEN-LAST:event_jLabel_accountMouseClicked

    private void jLabel_accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_accountMouseEntered
        // TODO add your handling code here:
        jLabel_account.setText("<html><u><b>账号管理</b></u></html>");
    }//GEN-LAST:event_jLabel_accountMouseEntered

    private void jLabel_accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_accountMouseExited
        // TODO add your handling code here:
        jLabel_account.setText("账号管理");
    }//GEN-LAST:event_jLabel_accountMouseExited

    private void jLabel_logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logOutMouseEntered
        // TODO add your handling code here:
        jLabel_logOut.setText("<html><u><b>注销</b><u></html>");
    }//GEN-LAST:event_jLabel_logOutMouseEntered

    private void jLabel_logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logOutMouseExited
        // TODO add your handling code here:
        jLabel_logOut.setText("注销");
    }//GEN-LAST:event_jLabel_logOutMouseExited

    private void jLabel_logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logOutMouseClicked
        // TODO add your handling code here:
        LoginUI T = new LoginUI();
        T.setLocationRelativeTo(null);
        T.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_logOutMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel_search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_search1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_search1MouseClicked

    private void jLabel_search2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_search2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_search2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox_stuDepart1;
    private javax.swing.JComboBox<String> jComboBox_teaDepart;
    private javax.swing.JLabel jLabel_account;
    private javax.swing.JLabel jLabel_hello;
    private javax.swing.JLabel jLabel_logOut;
    private javax.swing.JLabel jLabel_search1;
    private javax.swing.JLabel jLabel_search2;
    private javax.swing.JPanel jPanel_account;
    private javax.swing.JPanel jPanel_course;
    private javax.swing.JPanel jPanel_student;
    private javax.swing.JPanel jPanel_teacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_student;
    private javax.swing.JTable jTable_teacher;
    private javax.swing.JTextField jTextField_stuID1;
    private javax.swing.JTextField jTextField_stuMajor1;
    private javax.swing.JTextField jTextField_stuName1;
    private javax.swing.JTextField jTextField_teaID;
    private javax.swing.JTextField jTextField_teaMajor;
    private javax.swing.JTextField jTextField_teaName;
    // End of variables declaration//GEN-END:variables
}
